---
apiVersion: v2
appVersion: 2022.7.7
description: Home Assistant
name: home-assistant
version: 14.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - home-assistant
  - hass
  - homeassistant
home: https://github.com/bjw-s/helm-charts/tree/master/charts/stable/home-assistant
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/519px-Home_Assistant_Logo.svg.png
sources:
  - https://github.com/home-assistant/home-assistant
  - https://github.com/cdr/code-server
  - https://github.com/bjw-s/helm-charts/tree/master/charts/stable/home-assistant
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 4.4.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: "**BREAKING**: Remove database subcharts"
    - kind: changed
      description: Upgraded `influxdb` chart dependency to version 5.3.5
