---
apiVersion: v2
description: A common powered chart template. This can be useful for small projects that don't have their own chart.
name: app-template
version: 2.0.0-beta.1
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.0-beta.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |
        Updated library version to 2.0.0-beta.2.
      links:
        - name: Common library chart definition
          url: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/Chart.yaml
