---
apiVersion: v2
appVersion: v0.19
description: DNS proxy as ad-blocker for local network
name: blocky
version: 10.7.0
kubeVersion: ">=1.19.0-0"
keywords:
  - blocky
  - adblock
  - dns
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/blocky
icon: https://github.com/0xERR0R/blocky/raw/master/docs/blocky.svg?sanitize=true
sources:
  - https://github.com/0xERR0R/blocky
maintainers:
  - name: j0sh3rs
    email: github@beholdthehurricane.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.1.0
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.1.4
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Adjust startup probe delay
