---
apiVersion: v2
appVersion: v0.19
description: DNS proxy as ad-blocker for local network
name: blocky
version: 10.6.2
kubeVersion: ">=1.19.0-0"
keywords:
  - blocky
  - adblock
  - dns
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/blocky
icon: https://github.com/0xERR0R/blocky/raw/master/docs/blocky.svg?sanitize=true
sources:
  - https://github.com/0xERR0R/blocky
maintainers:
  - name: j0sh3rs
    email: github@beholdthehurricane.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.13.1
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Adjust startup probe delay
