---
apiVersion: v2
appVersion: v0.20
description: DNS proxy as ad-blocker for local network
name: blocky
version: 10.10.0
kubeVersion: '>=1.19.0-0'
keywords:
  - blocky
  - adblock
  - dns
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/blocky
icon: https://github.com/0xERR0R/blocky/raw/master/docs/blocky.svg?sanitize=true
sources:
  - https://github.com/0xERR0R/blocky
maintainers:
  - name: j0sh3rs
    email: j0sh3rs@pm.me
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.2.2
