config: |
  upstream:
    default:
      - tcp-tls:1.1.1.1:853
      - tcp-tls:8.8.8.8:853

  bootstrapDns: tcp+udp:1.1.1.1

service:
  dns-udp:
    enabled: true
    type: NodePort
    externalTrafficPolicy: Local
    ports:
      dns-udp:
        enabled: true
        port: 53
        protocol: UDP
        targetPort: 53
