---
apiVersion: v2
appVersion: 2.1.3
description: Collect ALL UniFi Controller, Site, Device & Client Data - Export to InfluxDB or Prometheus
name: unifi-poller
version: 11.5.0
kubeVersion: '>=1.16.0-0'
keywords:
  - unifi
  - unifi-poller
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/unifi-poller
icon: https://raw.githubusercontent.com/wiki/unifi-poller/unifi-poller/images/unifi-poller-logo.png
sources:
  - https://github.com/unifi-poller/unifi-poller
  - https://hub.docker.com/r/golift/unifi-poller
maintainers:
  - name: j0sh3rs
    email: github@beholdthehurricane.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Drop InfluxDB chart dependency
