---
apiVersion: v2
appVersion: 2.1.3
description: Collect ALL UniFi Controller, Site, Device & Client Data - Export to InfluxDB or Prometheus
name: unifi-poller
version: 11.1.3
kubeVersion: ">=1.16.0-0"
keywords:
  - unifi
  - unifi-poller
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/unifi-poller
icon: https://raw.githubusercontent.com/wiki/unifi-poller/unifi-poller/images/unifi-poller-logo.png
sources:
  - https://github.com/unifi-poller/unifi-poller
  - https://hub.docker.com/r/golift/unifi-poller
maintainers:
  - name: j0sh3rs
    email: j0sh3rs@pm.me
dependencies:
  - name: common
    repository: https://j0sh3rs.github.io/helm-charts
    version: 4.5.3
  - name: influxdb
    version: 5.4.1
    repository: https://charts.bitnami.com/bitnami
    condition: influxdb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
