---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 1.2.1
kubeVersion: ">=1.22.0-0"
keywords:
  - common
  - library
home: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: Fixed indentation in cronjob component to allow podAnnotations
    - kind: fixed
      description: Cleaned leftover `secret` behavior under `envFrom`.
      links:
        - name: GitHub Issue
          url: https://github.com/bjw-s/helm-charts/issues/94
    - kind: changed
      description: Updated code-server image tag to 4.9.1
