---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 1.5.0
kubeVersion: ">=1.22.0-0"
keywords:
  - common
  - library
home: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: support for for hostPID
    - kind: added
      description: support for for hostPID
    - kind: added
      description: Add support for CronJob backoffLimit
    - kind: changed
      description: Omit replicas field in Deployment if null is given
    - kind: changed
      description: Updated code-server image tag to v4.12.0
    - kind: changed
      description: Updated netshoot image tag to v0.10
