---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 2.0.1
kubeVersion: ">=1.22.0-0"
keywords:
  - common
  - library
home: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: |-
        Mounting of volumeClaimTemplates was not implemented.
    - kind: fixed
      description: |-
        advancedMounts for initContainers resulted in an error.
