---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 2.3.0
kubeVersion: ">=1.22.0-0"
keywords:
  - common
  - library
home: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: |-
        Add support for `appProtocol` in Kubernetes services.
    - kind: added
      description: |-
        Add support for route filters for HTTPRoute and GRPCRoute
    - kind: added
      description: |-
        Add support `dataSource` field in StatefulSet volumeClaimTemplates
    - kind: fixed
      description: |-
        GRPCRoute support for matches was not supported.
