---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 3.2.0
kubeVersion: ">=1.22.0-0"
keywords:
  - common
  - library
home: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: |-
        Support templating in annotation and label values for all objects
    - kind: added
      description: |-
        Support activeDeadlineSeconds field on CronJobs and Jobs
    - kind: added
      description: |-
        Support excluding secrets and configMaps from pod checksum annotation
    - kind: fixed
      description: |-
        Fixed failing ServiceMonitor test
    - kind: fixed
      description: |-
        Fixed networkPolicies not rendering correctly
