---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 2.4.0
kubeVersion: ">=1.22.0-0"
keywords:
  - common
  - library
home: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: |-
        Defaulting image tags to chart.Appversion was removed without a proper alternative
    - kind: fixed
      description: |-
        Using RequestRedirect is not allowed with BackendRefs in Routes.
    - kind: changed
      description: |-
        routes will no longer auto target its service.
        It will need to be explicitly defined as below

        ```yaml
        - backendRefs:
            - group: ""
              kind: Service
              name: foo
              namespace: foo-namespace
              port: 8080
              weight: 1
        ```
