apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 4.5.3
kubeVersion: ">=1.16.0-0"
keywords:
  - common
  - library
home: https://github.com/j0sh3rs/helm-charts/tree/main/charts/library/common
maintainers:
  - name: j0sh3rs
    email: j0sh3rs@pm.me
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Initial version
