name: "Collect changes"
description: "Collects and stores changed files/charts"

outputs:
  changesDetected:
    description: "Whether or not changes to charts have been detected"
    value: ${{ steps.filter.outputs.addedOrModified }}
  addedOrModifiedFiles:
    description: "A list of the files changed"
    value: ${{ steps.filter.outputs.addedOrModified_files }}
  addedOrModifiedCharts:
    description: "A list of the charts changed"
    value: ${{ steps.changed-charts.outputs.addedOrModifiedCharts }}

runs:
  using: "composite"
  steps:
    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.2.1

    - name: Collect changed files
      uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: shell
        filters: |
          addedOrModified:
            - added|modified: '**'

    - name: Collect changed charts
      id: changed-charts
      shell: bash
      run: |
        CHARTS=$(ct list-changed --config .ci/ct/ct-lint.yaml)
        # Set output to changed charts
        printf "::set-output name=addedOrModifiedCharts::%s\n" "${CHARTS[*]}"
