controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 29
          pullPolicy: IfNotPresent

        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true

      second_container:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 29

      third_container:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 29

  second_controller:
    type: deployment
    containers:
      main:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 29
          pullPolicy: IfNotPresent

ingress:
  main:
    enabled: true

persistence:
  config:
    enabled: true

  data:
    type: configMap
    name: myConfigMap
    advancedMounts:
      main: # the controller with whe "main" identifier
        main: # the container with whe "main" identifier
          - path: /data/config.yaml
            readOnly: false
            subPath: config.yaml
        second_container: # the container with whe "second_container" identifier
          - path: /appdata/config
            readOnly: true
      second_controller: # the controller with whe "second_controller" identifier
        main: # the container with whe "main" identifier
          - path: /data/config.yaml
            readOnly: false
            subPath: config.yaml
