controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 31
          pullPolicy: IfNotPresent

        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true

ingress:
  main:
    hosts:
      - host: "test.local"
        paths:
          - path: /
            service:
              name: main
              port: http
    tls:
      - hosts:
          - "test.local"

persistence:
  config:
    enabled: true
  media:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
