image:
  repository: b4bz/homer
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  main:
    enabled: true

probes:
  liveness:
    enabled: true
  readiness:
    enabled: true
  startup:
    enabled: true
