controllers:
  main:
    type: statefulset

    statefulset:
      volumeClaimTemplates:
        - name: config
          accessMode: ReadWriteOnce
          size: 1Gi
          storageClass: ceph-block
          advancedMounts:
            init-config:
              - path: /config
                readOnly: true

    initContainers:
      init-config:
        image:
          repository: public.ecr.aws/docker/library/busybox
          tag: latest
          pullPolicy: IfNotPresent
        command:
          - echo "success"

    containers:
      main:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 30
          pullPolicy: IfNotPresent

persistence:
  config-file:
    enabled: true
    type: configMap
    name: http-https-echo-configmap
    advancedMounts:
      main:
        init-config:
          - path: /tmp/config
            readOnly: true

service:
  main:
    enabled: false
