---
apiVersion: v2
appVersion: v10.286.0
description: An easy-to-deploy Dockerized Foundry Virtual Tabletop server
name: foundryvtt
version: 3.7.1
kubeVersion: ">=1.16.0-0"
keywords:
  - foundryvtt
home: https://github.com/felddy/foundryvtt-docker
icon: https://raw.githubusercontent.com/felddy/foundryvtt-docker/develop/assets/logo.png
sources:
  - https://github.com/felddy/foundryvtt-docker
maintainers:
  - name: j0sh3rs
    email: j0sh3rs@pm.me
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.2.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.1.0
