---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vaultwarden
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      # -- Version of the app-template helm chart
      # this example is not automatically updated, so be sure to use the latest chart version
      version: 0.1.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    controllers:
      main:
        strategy: Recreate

        containers:
          main:
            image:
              # -- image repository
              repository: vaultwarden/server
              # -- image tag
              # this example is not automatically updated, so be sure to use the latest image
              tag: 1.25.2
              # -- image pull policy
              pullPolicy: IfNotPresent

            # -- environment variables.
            # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
            env:
              # -- Config dir
              DATA_FOLDER: "config"

    # -- Configures service settings for the chart.
    service:
      main:
        ports:
          http:
            port: &port 80
          websocket:
            enabled: true
            port: &websocket-port 3012

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      main:
        enabled: true
        hosts:
          - host: chart-example.local
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  name: main
                  port: http
              - path: /notifications/hub
                pathType: Prefix
                service:
                  name: main
                  port: websocket

  route:
    # -- Enable and configure route settings for the chart under this key.
    main:
      enabled: true
      parentRefs:
        - name: gateway
          namespace: gateway-namespace
          sectionName: gateway-section
      hostnames:
        - chart-example.local
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - kind: Service
              port: *port
              name: *app
              namespace: default
              weight: 1
        - matches:
            - path:
                type: PathPrefix
                value: /notifications/hub/negotiate
          backendRefs:
            - kind: Service
              port: *port
              name: *app
              namespace: default
              weight: 1
        - matches:
            - path:
                type: PathPrefix
                value: /notifications/hub
          backendRefs:
            - kind: Service
              port: *websocket-port
              name: *app
              namespace: default
              weight: 1

    # -- Configure persistence settings for the chart under this key.
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /config
