---
controllers:
  main:
    containers:
      main:
        strategy: RollingUpdate
        image:
          repository: ghcr.io/bjw-s/k8s-ycl
          tag: "{{ .Chart.AppVersion }}"
          pullPolicy: Always

webhook:
  path: /mutate--v1-pod

  ignoreOwnNamespace: true
  ignoredNamespaces:
    - kube-system
