---
apiVersion: v2
appVersion: 1.26.0
description: Vaultwarden is a Bitwarden compatable server in Rust
name: vaultwarden
version: 5.8.0
kubeVersion: '>=1.16.0-0'
keywords:
  - Vaultwarden
  - bitwardenrs
home: 'https://github.com/k8s-at-home/charts/tree/master/charts/stable/vaultwarden'
icon: 'https://sesoodan.sirv.com/bitwarden_rs.png'
sources:
  - https://github.com/dani-garcia/vaultwarden
maintainers:
  - name: j0sh3rs
    email: j0sh3rs@pm.me
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.2.2
