---
controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 30
          pullPolicy: IfNotPresent

service:
  main:
    ports:
      http:
        port: 8080
