name: "Test action"

concurrency: helm-release

on:
  workflow_dispatch:
    inputs:
      chart:
        description: "Chart to release"
        default: ""
        required: false
  push:
    branches:
      - development
    paths:
      - "charts/**"

jobs:
  release-charts:
    name: Release charts
    runs-on: ubuntu-22.04
    steps:
      - name: Get k8s-at-home token
        id: get-app-token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.BJWS_APP_ID }}
          private_key: ${{ secrets.BJWS_APP_PRIVATE_KEY }}

      - name: Checkout charts branch
        uses: actions/checkout@v3
        with:
          token: ${{ steps.get-app-token.outputs.token }}
          path: "src"
          fetch-depth: 0

      - name: Collect charts to release
        uses: ./src/.github/actions/collect-charts
        id: collect-charts
        with:
          token: ${{ steps.get-app-token.outputs.token }}
          repoConfigFile: ./src/.ci/repo-config.yaml
          overrideCharts: "[${{ inputs.chart }}]"

      - name: Package Helm Charts
        shell: bash
        env:
          SRC_DIR: "src/charts"
        run: |
          CHARTS=( $(yq --null-input e '${{ steps.collect-charts.outputs.charts }}[]' ) )

          for CHART in "${CHARTS[@]}" ; do
            mapfile -t CHART_PATH_PARTS < <(echo "$CHART" | tr '/' '\n')
            CHART_TYPE=${CHART_PATH_PARTS[0]}

            echo "${SRC_DIR}/${CHART}"
          done
