name: "Charts: Release"

concurrency: helm-release

on:
  workflow_dispatch:
    inputs:
      charts:
        description: >
          Charts to release. Comma-separated string.
          Defaults to releasing everything.
        default: ""
        required: false
  push:
    branches:
      - main
    paths:
      - "charts/**"

env:
  HELM_VERSION: 3.9.2

jobs:
  prepare:
    name: Prepare data required for release
    runs-on: ubuntu-22.04
    outputs:
      token: ${{ steps.get-app-token.outputs.token }}
      charts-to-release: ${{ steps.collect-charts.outputs.charts }}
    steps:
      - name: Get k8s-at-home token
        id: get-app-token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.BJWS_APP_ID }}
          private_key: ${{ secrets.BJWS_APP_PRIVATE_KEY }}

      - name: Collect charts to release
        uses: ./src/.github/actions/collect-charts
        id: collect-charts
        with:
          token: ${{ inputs.token }}
          repoConfigFile: ./src/.ci/repo-config.yaml
          overrideCharts: "[${{ inputs.charts }}]"

  release-github-pages:
    name: Release Charts to GitHub pages
    uses: bjw-s/helm-charts/.github/workflows/charts-release-ghpages.yaml@main
    needs:
      - prepare
    with:
      charts: "[${{ needs.prepare.outputs.charts-to-release }}]"
