name: "Charts: Lint"

on:
  workflow_call:
    inputs:
      checkoutCommit:
        required: true
        type: string
      chartsToLint:
        description: >
          A JSON encoded array of charts to lint
        required: true
        default: '[]'
        type: string

env:
  HELM_VERSION: 3.9.2

jobs:
  lint-chart:
    if: ${{ inputs.chartsToLint != '[]' }}
    name: Lint chart
    strategy:
      matrix:
        chart: ${{ fromJSON(inputs.chartsToLint) }}
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkoutCommit }}

      - name: Verify chart version
        uses: ./.github/actions/verify-chart-version
        id: verify-chart-version
        with:
          chart: "charts/${{ matrix.chart }}"

      - name: Install Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.8.2
        with:
          setup-tools: |
            helmv3
          helm: "${{ env.HELM_VERSION }}"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (install)
        run: ct lint --config .ci/ct/ct.yaml --charts "charts/${{ matrix.chart }}"

  # Summarize matrix https://github.community/t/status-check-for-a-matrix-jobs/127354/7
  lint_success:
    needs:
      - lint-chart
    if: |
      always()
    name: Lint successful
    runs-on: ubuntu-22.04
    steps:
      - name: Check lint matrix status
        if: ${{ (inputs.chartsToLint != '[]') && (needs.lint-chart.result != 'success') }}
        run: exit 1
