name: "Charts: Release"

concurrency: helm-release

on:
  workflow_dispatch:
    inputs:
      charts:
        description: >
          Charts to release. Comma-separated string.
          Defaults to releasing everything.
        default: ""
        required: false

  push:
    branches:
      - main
    paths:
      - "charts/**"

env:
  HELM_VERSION: 3.9.2

jobs:
  prepare:
    name: Prepare data required for release
    runs-on: ubuntu-22.04
    outputs:
      libraryChartsToRelease: ${{ steps.collect-charts.outputs.chartsLibrary }}
      applicationChartsToRelease: ${{ steps.collect-charts.outputs.chartsApplication }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Collect charts to release
        uses: bjw-s/helm-charts-actions/collect-charts@main
        id: collect-charts
        with:
          repoConfigFile: ./.ci/repo-config.yaml
          overrideCharts: "[${{ inputs.charts }}]"

  release-gh-pages-library:
    name: Release Library charts to GitHub pages
    uses: ./.github/workflows/charts-release-ghpages.yaml
    needs:
      - prepare
    with:
      charts: "${{ needs.prepare.outputs.libraryChartsToRelease }}"
    secrets: inherit

  # release-gh-pages:
  #   name: Release Application Charts to GitHub pages
  #   uses: ./.github/workflows/charts-release-ghpages.yaml
  #   needs:
  #     - prepare
  #     - release-gh-pages-library
  #   with:
  #     charts: "${{ needs.prepare.outputs.applicationChartsToRelease }}"
  #   secrets: inherit
