name: "Charts: Lint"

on:
  workflow_call:
    inputs:
      checkoutCommit:
        required: true
        type: string
      chartChangesDetected:
        required: true
        type: string

jobs:
  lint:
    name: Lint charts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkoutCommit }}

      - name: Install Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.8.2
        with:
          setup-tools: |
            helmv3
          helm: "3.8.0"

      - name: Install Helm
        uses: Azure/setup-helm@v3.3

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Collect changes
        id: list-changed
        if: inputs.chartChangesDetected == 'true'
        run: |
          EXCLUDED=$(yq eval -o=json '.excluded-charts // []' .ci/ct/ct-lint.yaml)
          CHARTS=$(ct list-changed --config .ci/ct/ct-lint.yaml)
          CHARTS_JSON=$(echo "${CHARTS}" | jq -R -s -c 'split("\n")[:-1]')
          OUTPUT_JSON=$(echo "{\"excluded\": ${EXCLUDED}, \"all\": ${CHARTS_JSON}}" | jq -c '.all-.excluded')
          echo ::set-output name=charts::${OUTPUT_JSON}
          if [[ $(echo ${OUTPUT_JSON} | jq -c '. | length') -gt 0 ]]; then
            echo "::set-output name=detected::true"
          fi

      - name: Run chart-testing (lint)
        id: lint
        if: steps.list-changed.outputs.detected == 'true'
        run: ct lint --config .ci/ct/ct-lint.yaml
