name: "Charts: Test"

on:
  workflow_call:
    inputs:
      checkoutCommit:
        required: true
        type: string
      chartChanges:
        required: true
        type: string

jobs:
  # unit-test:
  #   name: Run unit tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #         ref: ${{ inputs.checkoutCommit }}

  #     - name: Install Kubernetes tools
  #       uses: yokawasa/action-setup-kube-tools@v0.8.2
  #       with:
  #         setup-tools: |
  #           helmv3
  #         helm: "3.8.0"

  #     - name: Install Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7

  #     - name: Install dependencies
  #       env:
  #         RUBYJQ_USE_SYSTEM_LIBRARIES: 1
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install libjq-dev
  #         bundle install

  #     - name: Run tests
  #       run: |
  #         bundle exec m -r ./test/

  generate-install-matrix:
    name: Generate matrix for install
    runs-on: ubuntu-latest
    outputs:
      matrix: |
        {
          "chart": ${{ steps.list-changed.outputs.charts }},
          "k8s_version": ["v1.21", "v1.24"]
        }
      detected: ${{ steps.list-changed.outputs.detected }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkoutCommit }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        if: inputs.chartChanges != ''
        run: |
          EXCLUDED=$(yq eval '.excluded-charts-install | join(",")' .ci/ct/ct.yaml)
          CHARTS=$(ct list-changed --config .ci/ct/ct.yaml --excluded-charts "${EXCLUDED}")
          OUTPUT_JSON=$(echo "${CHARTS}" | jq -R -s -c 'split("\n")[:-1]')
          echo ::set-output name=charts::${OUTPUT_JSON}
          if [[ $(echo ${OUTPUT_JSON} | jq -c '. | length') -gt 0 ]]; then
            echo "::set-output name=detected::true"
          fi

  install-charts:
    needs:
      - generate-install-matrix
    if: needs.generate-install-matrix.outputs.detected == 'true'
    name: Install charts
    strategy:
      matrix: ${{ fromJson(needs.generate-install-matrix.outputs.matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkoutCommit }}

      - name: Install Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.8.2
        with:
          setup-tools: |
            helmv3
            kubectl
          helm: "3.6.3"
          kubectl: "${{ matrix.k8s_version }}"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Create k3d cluster
        uses: nolar/setup-k3d-k3s@v1
        with:
          version: ${{ matrix.k8s_version }}

      - name: Remove node taints
        run: |
          kubectl taint --all=true nodes node.cloudprovider.kubernetes.io/uninitialized- || true

      - name: Run chart-testing (install)
        run: ct install --config .ci/ct/ct.yaml --charts ${{ matrix.chart }}

  # Summarize matrix https://github.community/t/status-check-for-a-matrix-jobs/127354/7
  install_success:
    needs:
      - generate-install-matrix
      - install-charts
    if: |
      always()
    name: Install successful
    runs-on: ubuntu-latest
    steps:
      - name: Check install matrix status
        if: ${{ (needs.generate-install-matrix.outputs.detected == 'true') && (needs.install-charts.result != 'success') }}
        run: exit 1
