name: "Pull Request: Validate"

on:
  pull_request:
    branches:
      - main
      - development
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  pr-metadata:
    uses: ./.github/workflows/pr-metadata.yaml

  pre-commit-check:
    uses: ./.github/workflows/pre-commit-check.yaml
    needs:
      - pr-metadata
    with:
      modifiedFiles: ${{ needs.pr-metadata.outputs.addedOrModifiedFiles }}

  # charts-changelog:
  #   uses: ./.github/workflows/charts-changelog.yaml@main
  #   needs:
  #     - pr-metadata
  #     - pre-commit-check
  #   with:
  #     isRenovatePR: ${{ needs.pr-metadata.outputs.isRenovatePR }}
  #     modifiedCharts: ${{ needs.pr-metadata.outputs.addedOrModifiedCharts }}

  charts-lint:
    uses: ./.github/workflows/charts-lint.yaml
    needs:
      - pr-metadata
      # - charts-changelog
    with:
      checkoutCommit: ${{ github.sha }}
      chartsToLint: ${{ needs.pr-metadata.outputs.chartsToLint }}

  charts-test:
    uses: ./.github/workflows/charts-test.yaml
    needs:
      - pr-metadata
      # - charts-changelog
    with:
      checkoutCommit: ${{ github.sha }}
      chartsToTest: ${{ needs.pr-metadata.outputs.chartsToInstall }}
